---
name: 'Check PIP licences'
description: 'Check for allowed licenses on pip packages.'
runs:
  using: 'composite'
  steps:
    - run: check_pip_licenses
      shell: bash
inputs:
  requirements_file:
    description: "Requirements file path"
    required: false
    default: 'requirements.txt'


