---
name: 'Check PIP licences'
description: 'Check for allowed licenses on pip packages.'
runs:
  using: 'composite'
  steps:
    - run: pip install pip-licenses==3.5.4
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: check_pip_licenses
      shell: bash
inputs:
  requirements_file:
    description: "Requirements file path"
    required: false
    default: 'requirements.txt'
