#!/usr/bin/env python

import sys

from piplicenses import main

INTERNAL_PACKAGES = [
  'cc-tools',
  'cc-tools-db',
  'cc-tools-kafka',
  'cc-tools-monitoring',
  'cc-tools-redis',
  'cc-tools-web',
]

IGNORED_PACKAGES = [
  *INTERNAL_PACKAGES,
  'aiopath',
  'aiofiles',
  'ansible',
  'ansible-core',
  'facebook-business',
  'GPy',
  'GPyOpt',
  'numexpr',
  'pathable',
  'types-orjson',
]

ALLOWED_LICENSES = [
    '3-Clause BSD License',
    'Apache 2',
    'Apache 2.0',
    'Apache License',
    'Apache License, Version 2.0',
    'Apache License 2.0',
    'Apache Software License',
    'Apache Software License, BSD License',
    'Apache Software License, MIT License',
    'Apache-2.0 OR MIT',
    'BSD 3-Clause',
    'BSD License, Apache Software License',
    'BSD License',
    'BSD-3-Clause',
    'BSD',
    'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
    'Eclipse Public License v2.0',
    'GNU General Public License (GPL)',
    'GNU General Public License v2 (GPLv2)',
    'GNU General Public License v2 or later (GPLv2+)',
    'GNU General Public License v3 (GPLv3)',
    'GNU General Public License v3 or later (GPLv3+)',
    'GNU Lesser General Public License v2 (LGPLv2)',
    'GNU Lesser General Public License v3 or later (LGPLv3+)',
    'GNU Library or Lesser General Public License (LGPL)',
    'Historical Permission Notice and Disclaimer (HPND)',
    'ISC License (ISCL)',
    'ISC',
    'MIT License',
    'MIT License, Apache Software License',
    'MIT',
    'Mozilla Public License 2.0 (MPL 2.0)',
    'new BSD',
    'Public Domain',
    'Python Software Foundation License',
    'The Unlicense (Unlicense)',
    'Zope Public License',
]


def check() -> None:
    licenses = ';'.join(ALLOWED_LICENSES)
    sys.argv.append(f'--allow-only={licenses}')
    sys.argv.extend(['--ignore-packages', *IGNORED_PACKAGES])

    sys.exit(main())


if __name__ == '__main__':
    check()
